task:
  name: CSS Lint
  container:
    image: node:latest
  auto_cancellation: false
  Install_Tool_script:
    - npm install -g csslint
  script:
    - find . -name \*.css -exec csslint {} \;

task:
  name: Build Site
  container:
    image: ruby:latest
  auto_cancellation: true
  Install_Jekyll_script:
    - gem install github-pages
  script:
    - jekyll build
    - jekyll doctor
