task:
  name: CSS Lint
  container:
    image: node:latest
  auto_cancellation: false
  Install_Tool_script:
    - npm install -g csslint
  script:
    - find . -name \*.css -exec csslint {} \;

task:
  name: HTML Lint
  container:
    image: node:latest
  auto_cancellation: false
  Install_Tool_script:
    - npm i -g html-lint
  script:
    - node html-lint --strict --verbose https://am-i-cool.pw
