task:
  name: CSS Lint
  container:
    image: node:latest
  auto_cancellation: false
  Install_Tool_script:
    - npm install -g csslint
  script:
    - find . -name \*.css -exec csslint {} \;

task:
  name: Build Site
  container:
    image: ruby:latest
  auto_cancellation: true
  Install_Jekyll_script:
    - gem install github-pages
  Gem1_cache:
    folder: /usr/local/bundle
  Gem2_cache:
    folder: /root/.gem/ruby/2.6.0
  Gem3_cache:
    folder: /usr/local/lib/ruby/gems/2.6.0
  script:
    - jekyll build
    - jekyll doctor
