task:
  name: CSS Lint
  container:
    image: node:latest
  auto_cancellation: false
  Install_Tool_script:
    - npm install -g csslint
  script:
    - find . -name \*.css -exec csslint {} \;

task:
  name: Build Site
  container:
    image: ruby:latest
  auto_cancellation: true
  Gem_cache:
    folder: /usr/local/bundle
  Populate_script: gem install bundler && bundler install
  script:
    - bundler exec jekyll build
    - bundler exec jekyll doctor
